# MapleGrind 練功腳本相關設定
grind_settings:
  # 技能施放之間的隨機延遲範圍 (秒)
  skill_gap_time: [0.5, 1.0]

# 技能列表
skills:
  # 漩渦球球
  ball:
    key: 'pagedown'
    image: 'vortex_sphere.png'
  # 艾爾達斯降臨
  erdas:
    key: 'shift'
    image: 'erda_shower.png'
  # 風轉奇想
  wind:
    key: 'end'
    image: 'merciless_wind.png'
  # 小雞
  chicken:
    key: "'"
    image: 'phalanx_charge.png'
  # 龍捲風
  tornado:
    key: 'd'
    image: 'howling_gale.png'
  # 季風
  monsoon:
    key: 'b'
    image: 'monsoon.png'
  # 蜘蛛之鏡
  spider:
    key: 'f'
    image: 'true_arachnid_reflection.png'
  # 烈陽印記
  sun:
    key: 'f5'
    image: 'solar_crest.png'
  # 西爾芙之壁
  shield:
    key: '6'
    image: 'gale_barrier.png'
  # 武公
  mu_gong:
    key: 'f2'
    image: 'mu_gong.png'
  # 一鍵爆發
  aio:
    key: 'f1'
    image: 'aio.png'
  # 阿涅摩依
  anemoi:
    key: 'v'
    image: 'anemoi.png'

  # --- 以下為備用或已停用的技能 ---
  # 爆擊強化
  # vicious:
  #   key: 'f3'
  #   image: 'vicious_shot.png'
  # 暴風加護
  # big_arrow:
  #   key: 'f4'
  #   image: 'storm_whim.png'

# Boss列表
boss:
  # 炎魔
  zakum: 'schedule_daily_boss_zakum_tab.png'
  # 梅格耐斯
  magnus: 'schedule_daily_boss_magnus_tab.png'
  # 希拉
  hilla: 'schedule_daily_boss_hilla_tab.png'
  # 比艾樂
  pierre: 'schedule_daily_boss_pierre_tab.png'
  # 斑斑
  von_bon: 'schedule_daily_boss_von_bon_tab.png'
  # 血腥皇后
  crimson_queen: 'schedule_daily_boss_crimson_queen_tab.png'
  # 貝倫
  vellum: 'schedule_daily_boss_vellum_tab.png'
  # 凡雷恩
  von_leon: 'schedule_daily_boss_von_leon_tab.png'
  # 闇黑龍王
  horntail: 'schedule_daily_boss_horntail_tab.png'
  # 阿卡伊農
  arkarium: 'schedule_daily_boss_arkarium_tab.png'
  # 粉豆
  pink_bean: 'schedule_daily_boss_pink_bean_tab.png'
  # 培羅德
  gollux: 'schedule_daily_boss_gollux_tab.png'

# 倉庫列表
storage:
  '1': '1.png'
  '2': '2.png'
  '3': '3.png'
  '4': '4.png'
  '5': '5.png'
  '6': '6.png'
  '7': '7.png'
  '8': '8.png'
  '9': '9.png'
  '0': '0.png'

# 活動跳舞機
dancing:
  left: 'direction_left.png'
  right: 'direction_right.png'
  down: 'direction_down.png'
  up: 'direction_up.png'

# 跳舞機相關的UI
dancing_ui:
  ending_npc: 'end_npc.png'
  start_ui: 'end.png'

# UI相關的位置與大小設定 (Magic Numbers)
ui_offsets:
  minimap:
    x: 15
    y: 99
    width: 182
    height: 71