# MapleGrind 練功腳本相關設定
grind_settings:
  # 技能施放之間的隨機延遲範圍 (秒)
  skill_gap_time: [0.5, 1.0]

# 技能列表
skills:
  # 漩渦球球
  ball:
    key: 'pagedown'
    image: 'vortex_sphere.png'
  # 艾爾達斯降臨
  erdas:
    key: 'shift'
    image: 'erda_shower.png'
  # 風轉奇想
  wind:
    key: 'end'
    image: 'merciless_wind.png'
  # 小雞
  chicken:
    key: "'"
    image: 'phalanx_charge.png'
  # 龍捲風
  tornado:
    key: 'd'
    image: 'howling_gale.png'
  # 季風
  monsoon:
    key: 'b'
    image: 'monsoon.png'
  # 蜘蛛之鏡
  spider:
    key: 'f'
    image: 'true_arachnid_reflection.png'
  # 烈陽印記
  sun:
    key: 'f5'
    image: 'solar_crest.png'
  # 西爾芙之壁
  shield:
    key: '6'
    image: 'gale_barrier.png'
  # 武公
  mu_gong:
    key: 'f2'
    image: 'mu_gong.png'
  # 一鍵爆發
  aio:
    key: 'f1'
    image: 'aio.png'
  # 阿涅摩依
  anemoi:
    key: 'v'
    image: 'anemoi.png'

  # --- 以下為備用或已停用的技能 ---
  # 爆擊強化
  # vicious:
  #   key: 'f3'
  #   image: 'vicious_shot.png'
  # 暴風加護
  # big_arrow:
  #   key: 'f4'
  #   image: 'storm_whim.png'

# Boss列表
boss:
  # 炎魔
  zakum: 'schedule_daily_boss_zakum_tab.png'
  # 梅格耐斯
  magnus: 'schedule_daily_boss_magnus_tab.png'
  # 希拉
  hilla: 'schedule_daily_boss_hilla_tab.png'
  # 比艾樂
  pierre: 'schedule_daily_boss_pierre_tab.png'
  # 斑斑
  von_bon: 'schedule_daily_boss_von_bon_tab.png'
  # 血腥皇后
  crimson_queen: 'schedule_daily_boss_crimson_queen_tab.png'
  # 貝倫
  vellum: 'schedule_daily_boss_vellum_tab.png'
  # 凡雷恩
  von_leon: 'schedule_daily_boss_von_leon_tab.png'
  # 闇黑龍王
  horntail: 'schedule_daily_boss_horntail_tab.png'
  # 阿卡伊農
  arkarium: 'schedule_daily_boss_arkarium_tab.png'
  # 粉豆
  pink_bean: 'schedule_daily_boss_pink_bean_tab.png'
  # 培羅德
  gollux: 'schedule_daily_boss_gollux_tab.png'

# 倉庫列表
storage:
  numbers:
    '1': '1.png'
    '2': '2.png'
    '3': '3.png'
    '4': '4.png'
    '5': '5.png'
    '6': '6.png'
    '7': '7.png'
    '8': '8.png'
    '9': '9.png'
    '0': '0.png'
  
  ui:
    title: 'storage/storage_ui.png'
    confirm: 'storage/storage_confirm.png'
    icon: 'storage/storage_icon.png'
    inventory: 'storage/inventory.png'

# 活動跳舞機
dancing:
  left: 'direction_left.png'
  right: 'direction_right.png'
  down: 'direction_down.png'
  up: 'direction_up.png'

# 跳舞機相關的UI
dancing_ui:
  ending_npc: 'end_npc.png'
  start_ui: 'end.png'
  event_tab: 'dancing_event_tab.png'
  participate_button: 'participate.png'

# UI相關的位置與大小設定 (Magic Numbers)
ui_offsets:
  minimap:
    x: 15
    y: 99
    width: 182
    height: 71

# 一個獨立的市場icon，用於打開總覽視窗時辨識用
menu:
  menu_market_icon: 'market.png'

daily_prepare:
  common:
    menu_market_icon: 'market.png'
    schedule_weekly_tab: 'schedule_weekly_tab.png'
    schedule_boss_tab: 'schedule_boss_tab.png'
    item_others_tab: 'item_others_tab.png'

  settings:
    daily_set: 'daily_set.png'
    daily_apply: 'daily_apply.png'
    confirm_popup: 'confirm_daily_pop_up.png'
    buff_storm: 'storm_elemental.png'
    buff_trifling: 'trifling_wind.png'
    buff_guided_arrow: 'guided_arrow.png'

  union:
    get_coin: 'get_coin.png'
    artifact_tab: 'union_artifact_tab.png'
    extend_button: 'extend_union_artifact_button.png'
    extend_error: 'extend_union_artifact_error_message.png'
    extend_confirm: 'extend_union_artifact_confirm_button.png'

  mission:
    daily_start: 'schedule_daily_all_start.png'
    daily_complete: 'schedule_daily_all_complete.png'
    panel_confirm: 'schedule_panel_confirm.png'
    daily_bonus: 'daily_bonus.png'
    weekly_start: 'weekly_mission_start_button.png'
    weekly_complete: 'complete_weekly_mission_button.png'

  dismantle:
    fast_travel: 'fast_travel.png'
    village_icon: 'ardentmill_village_icon.png'
    village_map_check: 'ardentmill.png'
    panel_button: 'disassemble_panel.png'
    put_armor: 'put_all_armor_on_table.png'
    empty_table: 'empty_disassembly_table.png'
    disassemble_button: 'disassemble.png'
    complete_popup: 'dismantle_complete.png'

  hd:
    receive_button: 'receive_hd_gift.png'
    all_received: 'all_hd_gifts_received.png'
    has_gift: 'hd_has_gift.png'
    take_coin: 'take_hd_coin.png'

  milestone:
    has_collectable: 'has_collectable_milestones.png'
    confirm: 'milestone_confirm_button.png'
    no_milestone: 'no_milestone.png'

  market:
    title: 'market_title.png'
    collectable_tab: 'market_collectable_tab.png'
    restock_all: 're_stock_all.png'
    restock_finish: 're_stock_finish.png'
    no_vacancy: 'no_vacancy_in_market.png'
    collect_money: 'collect_money.png'
    all_collectable: 'all_collectable.png'
    all_collected: 'all_collected.png'
    leave: 'leave_market.png'

  master_apprentice:
    title: 'master_and_apprentice_title.png'
    complete_button: 'master_and_apprentice_complete_button.png'

  housing:
    house_map_check: 'querencia.png'
    caretaker:  'caretaker.png'
    talk_with_caretaker: 'talk_with_caretaker.png'
    caretaker_talkable: 'caretaker_talkable.png'
    stop_conversation: 'stop_conversation.png'

  event:
    event_daily_checkin_tab: 'event/event_daily_checkin_tab.png'
    event_daily_checkin_tab_2: 'event/event_daily_checkin_tab_2.png'
    event_daily_checkin_ui_header: 'event/event_daily_checkin_ui_header.png'
    event_daily_checkin_ui_header_2: 'event/event_daily_checkin_ui_header_2.png'
    daily_check_in_button: 'event/daily_check_in_button.png'
    daily_check_in_button_2: 'event/daily_check_in_button_2.png'
    weekly_check_in_button: 'event/weekly_check_in_button.png'


monster_collection:
  title: 'monster_collection/monster_collection_title.png'
  adventure_tab: 'monster_collection/adventure_tab.png'
  reward_button: 'monster_collection/receive_monster_collection_reward.png'
  start_button: 'monster_collection/start_adventure.png'

daily_boss:
  ui:
    panel: 'boss_ui.png'
    move_button: 'boss_ui_move_to_boss_map_button.png'
    reference_scroll: 'boss_ui_von_leon.png'

  zakum:
    tab_pic: 'boss_ui_zakum.png'
    npc_adobis: 'adobis.png'
    map_check: 'zakum_map.png'
    item_eye: 'eye_of_fire.png'
    altar: 'zakum_map_stone.png'

  magnus:
    tab_pic: 'boss_ui_magnus.png'
    castle_map_icon: 'tyrants_castle_map_icon.png'
    map_check: 'magnus_map.png'

  hilla:
    tab_pic: 'boss_ui_hilla.png'
    tower_map_icon: 'hillas_tower_map_icon.png'

  arkarium:
    tab_pic: 'boss_ui_arkarium.png'
    
  # 其他 Boss 暫時只有 tab_pic，根據 boss_ui_{boss}.png 規則推導
#  pierre:
#    tab_pic: 'boss/boss_ui_pierre.png' # 假設檔案存在
#  von_bon:
#    tab_pic: 'boss/boss_ui_von_bon.png'
#  crimson_queen:
#    tab_pic: 'boss/boss_ui_crimson_queen.png'
#  vellum:
#    tab_pic: 'boss/boss_ui_vellum.png'
#  von_leon:
#    tab_pic: 'boss/boss_ui_von_leon.png'
#  horntail:
#    tab_pic: 'boss/boss_ui_horntail.png'
#  pink_bean:
#    tab_pic: 'boss/boss_ui_pink_bean.png'
#  gollux:
#    tab_pic: 'boss/boss_ui_gollux.png'