- action: key_down
  key: alt
  time: 0.828
- action: key_down
  key: up
  time: 0.938
- action: key_up
  key: alt
  time: 0.947
- action: key_down
  key: alt
  time: 1.156
- action: key_up
  key: alt
  time: 1.323
- action: key_up
  key: up
  time: 1.347
- action: key_down
  key: alt
  time: 2.395
- action: key_up
  key: alt
  time: 2.504
- action: key_down
  key: up
  time: 2.514
- action: key_down
  key: alt
  time: 2.739
- action: key_up
  key: alt
  time: 2.885
- action: key_up
  key: up
  time: 2.951
- action: key_down
  key: space
  time: 3.965
- action: key_up
  key: space
  time: 4.187
- action: key_down
  key: down
  time: 4.726
- action: key_down
  key: alt
  time: 4.832
- action: key_up
  key: alt
  time: 4.982
- action: key_up
  key: down
  time: 5.019
- action: key_down
  key: down
  time: 5.675
- action: key_down
  key: alt
  time: 5.709
- action: key_up
  key: alt
  time: 5.876
- action: key_up
  key: down
  time: 5.961
- action: key_down
  key: down
  time: 6.316
- action: key_down
  key: alt
  time: 6.337
- action: key_up
  key: alt
  time: 6.497
- action: key_up
  key: down
  time: 6.552
- action: key_down
  key: left
  time: 7.166
- action: key_up
  key: left
  time: 7.211
- action: key_down
  key: space
  time: 7.6
- action: key_up
  key: space
  time: 7.856
