- action: key_down
  key: alt
  time: 0.91
- action: key_down
  key: up
  time: 1.015
- action: key_up
  key: alt
  time: 1.02
- action: key_down
  key: alt
  time: 1.149
- action: key_up
  key: alt
  time: 1.344
- action: key_up
  key: up
  time: 1.432
- action: key_down
  key: down
  time: 2.183
- action: key_down
  key: alt
  time: 2.354
- action: key_up
  key: alt
  time: 2.46
- action: key_down
  key: alt
  time: 2.853
- action: key_up
  key: alt
  time: 2.989
- action: key_down
  key: alt
  time: 3.449
- action: key_up
  key: alt
  time: 3.586
- action: key_up
  key: down
  time: 3.845
