daily_prepare:
  daily_mission: false
  dismantle: true
  event: true
  hd_gift: false
  housing: false
  market: false
  master_apprentice: false
  milestone: false
  switch_set: false
  union_coin: false
grind_settings:
  stop_when_people_appears: true
  stop_when_rune_appears: true
grind_skills:
- enabled: true
  image_path: photos/skills/vortex_sphere.png
  key: pagedown
- enabled: true
  image_path: photos/skills/erda_shower.png
  key: shift
- enabled: true
  image_path: photos/skills/merciless_wind.png
  key: end
- enabled: true
  image_path: photos/skills/phalanx_charge.png
  key: ''''
- enabled: true
  image_path: photos/skills/howling_gale.png
  key: d
- enabled: true
  image_path: photos/skills/monsoon.png
  key: b
- enabled: true
  image_path: photos/skills/true_arachnid_reflection.png
  key: f
- enabled: true
  image_path: photos/skills/solar_crest.png
  key: f5
- enabled: true
  image_path: photos/skills/gale_barrier.png
  key: '6'
- enabled: true
  image_path: photos/skills/mu_gong.png
  key: f2
- enabled: true
  image_path: photos/skills/aio.png
  key: f1
- enabled: true
  image_path: photos/skills/anemoi.png
  key: v
- enabled: true
  image_path: photos/skills/元素風暴.png
  key: f8
